{"metadata":{"modules":[{"name":"WeatherSDK"}],"role":"collection","roleHeading":"Framework","externalID":"WeatherSDK","symbolKind":"module","title":"WeatherSDK"},"variants":[{"paths":["\/documentation\/weathersdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/weathersdk"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","anchor":"Overview","level":2,"type":"heading"}]}],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherForecastSDK"]},{"identifiers":["doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherForecastSDKDelegate"],"title":"Protocols"},{"title":"Enumerations","identifiers":["doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherForecastSDKError"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.sample.sdk.WeatherSDK/documentation/WeatherSDK":{"abstract":[],"identifier":"doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK","title":"WeatherSDK","url":"\/documentation\/weathersdk","type":"topic","kind":"symbol","role":"collection"},"doc://com.sample.sdk.WeatherSDK/documentation/WeatherSDK/WeatherForecastSDK":{"kind":"symbol","role":"symbol","url":"\/documentation\/weathersdk\/weatherforecastsdk","abstract":[{"type":"text","text":"The main class for interacting with the WeatherForecastSDK. This class is responsible for initializing the SDK and providing access to the weather forecast functionality."}],"title":"WeatherForecastSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WeatherForecastSDK"}],"type":"topic","navigatorTitle":[{"text":"WeatherForecastSDK","kind":"identifier"}],"identifier":"doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherForecastSDK"},"doc://com.sample.sdk.WeatherSDK/documentation/WeatherSDK/WeatherSDKVersionNumber":{"type":"topic","title":"WeatherSDKVersionNumber","kind":"symbol","url":"\/documentation\/weathersdk\/weathersdkversionnumber","identifier":"doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherSDKVersionNumber","fragments":[{"text":"WeatherSDKVersionNumber","kind":"identifier"}],"abstract":[{"text":"Project version number for WeatherSDK.","type":"text"}],"role":"symbol"},"doc://com.sample.sdk.WeatherSDK/documentation/WeatherSDK/WeatherSDKVersionString":{"abstract":[{"text":"Project version string for WeatherSDK.","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"WeatherSDKVersionString"}],"role":"symbol","kind":"symbol","url":"\/documentation\/weathersdk\/weathersdkversionstring","title":"WeatherSDKVersionString","identifier":"doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherSDKVersionString"},"doc://com.sample.sdk.WeatherSDK/documentation/WeatherSDK/WeatherForecastSDKError":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeatherForecastSDKError"}],"kind":"symbol","abstract":[{"type":"text","text":"An enumeration of possible errors that can occur within the WeatherForecastSDK."}],"title":"WeatherForecastSDKError","type":"topic","identifier":"doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherForecastSDKError","url":"\/documentation\/weathersdk\/weatherforecastsdkerror","navigatorTitle":[{"kind":"identifier","text":"WeatherForecastSDKError"}]},"doc://com.sample.sdk.WeatherSDK/documentation/WeatherSDK/WeatherForecastSDKDelegate":{"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"WeatherForecastSDKDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/weathersdk\/weatherforecastsdkdelegate","identifier":"doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherForecastSDKDelegate","navigatorTitle":[{"text":"WeatherForecastSDKDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"A delegate protocol to handle events in the WeatherForecastSDK."}],"title":"WeatherForecastSDKDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Variables","identifiers":["doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherSDKVersionNumber","doc:\/\/com.sample.sdk.WeatherSDK\/documentation\/WeatherSDK\/WeatherSDKVersionString"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}